import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

import apiClient from '@/lib/api/client';
import { useAuthStore } from '@/lib/stores/auth-store';
import { FeedbackToast } from '@/components/ui/feedback-toast';

type LocationState = {
  email?: string;
  password?: string;
};

export default function TwoFactorPage() {
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const location = useLocation();
  const navigate = useNavigate();
  const setAuth = useAuthStore((state) => state.setAuth);
  const state = (location.state as LocationState) || {};

  useEffect(() => {
    if (!state.email || !state.password) {
      navigate('/auth/login', { replace: true });
    }
  }, [state.email, state.password, navigate]);

  if (!state.email || !state.password) {
    return null;
  }

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (code.length !== 6) {
      setError('Enter the 6-digit code from your authenticator app.');
      return;
    }

    setError('');
    setLoading(true);

    try {
      const response = await apiClient.post('/auth/login', {
        email: state.email,
        password: state.password,
        twoFactorCode: code,
      });

      const { user, accessToken, requiresTwoFactor } = response.data;

      if (requiresTwoFactor) {
        setError('The code you entered is not valid. Try again.');
        return;
      }

      setAuth(user, accessToken);
      navigate('/', { replace: true });
    } catch (err: any) {
      setError(
        err?.response?.data?.message ??
          'We could not verify that code. Please try again.',
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      {error && (
        <FeedbackToast message={error} onDismiss={() => setError('')} tone="error" />
      )}

      <div className="flex min-h-screen items-center justify-center bg-muted px-4 py-12">
      <div className="w-full max-w-md space-y-6 rounded-xl border border-border bg-card p-8 shadow-sm">
        <div className="space-y-2 text-center">
          <h2 className="text-2xl font-semibold text-foreground">Two-Factor Authentication</h2>
          <p className="text-sm text-muted-foreground">
            Enter the 6-digit code generated by your authenticator app for{' '}
            <span className="font-medium text-foreground">{state.email}</span>.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">

          <div>
            <label className="mb-1 block text-xs font-semibold uppercase text-muted-foreground">
              Verification code
            </label>
            <input
              type="text"
              inputMode="numeric"
              maxLength={6}
              autoFocus
              value={code}
              onChange={(event) => {
                const next = event.target.value.replace(/[^0-9]/g, '').slice(0, 6);
                setCode(next);
              }}
              className="w-full rounded-lg border border-border px-3 py-2 text-center text-lg tracking-widest focus:border-transparent focus:ring-2 focus:ring-blue-500"
              placeholder="••••••"
              disabled={loading}
            />
          </div>

          <button
            type="submit"
            disabled={loading || code.length !== 6}
            className="inline-flex w-full items-center justify-center rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {loading ? 'Verifying…' : 'Verify & Sign In'}
          </button>

          <button
            type="button"
            onClick={() => navigate('/auth/login', { replace: true })}
            className="w-full text-sm font-medium text-muted-foreground transition hover:text-foreground"
            disabled={loading}
          >
            Use a different account
          </button>
        </form>
      </div>
    </div>
    </>
  );
}