import type { UserRole } from '@/types/users';

export const ALL_ROLES: UserRole[] = [
  'ADMIN',
  'SALESPERSON',
  'ACCOUNT_MANAGER',
  'RECRUITER',
  'HR',
  'EMPLOYEE',
];

export const ROLE_PERMISSIONS = {
  SELF_LEAVE_MANAGE: ['ADMIN', 'HR', 'ACCOUNT_MANAGER', 'EMPLOYEE'],
  LEAVE_APPROVAL: ['ADMIN', 'HR'],
  CRM_CUSTOMERS: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER'],
  CRM_CONTACTS: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER'],
  CRM_LEADS: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER'],
  CRM_OPPORTUNITIES: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER', 'RECRUITER'],
  CRM_CAMPAIGNS: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER'],
  RECRUITMENT: ['ADMIN', 'HR', 'RECRUITER'],
  EMPLOYEE_DIRECTORY: ['ADMIN', 'HR'],
  EOD_REPORTS: ['ADMIN', 'HR', 'EMPLOYEE'],
  LEAVE_REQUESTS: ['ADMIN', 'HR', 'EMPLOYEE'],
  PERFORMANCE_REVIEWS: ['ADMIN', 'HR', 'EMPLOYEE'],
  INVOICES: ['ADMIN', 'ACCOUNT_MANAGER'],
  INVOICE_DETAIL: ['ADMIN', 'ACCOUNT_MANAGER', 'SALESPERSON'],
  TASKS: ['ADMIN', 'ACCOUNT_MANAGER', 'SALESPERSON', 'HR', 'EMPLOYEE'],
  USER_MANAGEMENT: ['ADMIN'],
  COMPANY_SETTINGS: ['ADMIN', 'HR'],
  NOTIFICATION_SETTINGS: ALL_ROLES,
  INTEGRATIONS: ['ADMIN'],
  HOLIDAYS_SETTINGS: ['ADMIN', 'HR'],
} satisfies Record<string, UserRole[]>;


