import type { UserRole } from '@/types/users';

export const ALL_ROLES: UserRole[] = [
  'ADMIN',
  'SALESPERSON',
  'ACCOUNT_MANAGER',
  'RECRUITER',
  'HR',
  'EMPLOYEE',
];

export const ROLE_PERMISSIONS = {
  CRM_CUSTOMERS: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER'],
  CRM_CONTACTS: ['ADMIN', 'SALESPERSON'],
  CRM_LEADS: ['ADMIN', 'SALESPERSON'],
  CRM_OPPORTUNITIES: ['ADMIN', 'SALESPERSON', 'RECRUITER', 'HR'],
  CRM_CAMPAIGNS: ['ADMIN', 'SALESPERSON'],
  RECRUITMENT: ['ADMIN', 'HR', 'RECRUITER'],
  EMPLOYEE_DIRECTORY: ['ADMIN', 'HR'],
  EOD_REPORTS: ['ADMIN', 'HR', 'EMPLOYEE', 'ACCOUNT_MANAGER', 'SALESPERSON', 'RECRUITER'],
  LEAVE_REQUESTS: ['ADMIN', 'HR', 'EMPLOYEE', 'ACCOUNT_MANAGER', 'SALESPERSON', 'RECRUITER'],
  PERFORMANCE_REVIEWS: ['ADMIN', 'HR', 'EMPLOYEE', 'ACCOUNT_MANAGER', 'SALESPERSON', 'RECRUITER'],
  CHECK_INS: ['ADMIN', 'HR', 'EMPLOYEE', 'ACCOUNT_MANAGER', 'SALESPERSON', 'RECRUITER'],
  INVOICES: ['ADMIN', 'ACCOUNT_MANAGER'],
  INVOICE_DETAIL: ['ADMIN', 'ACCOUNT_MANAGER', 'SALESPERSON'],
  TASKS: ['ADMIN', 'ACCOUNT_MANAGER', 'SALESPERSON', 'HR', 'RECRUITER'],
  CALENDAR: ['ADMIN', 'SALESPERSON', 'ACCOUNT_MANAGER', 'RECRUITER', 'HR'],
  USER_MANAGEMENT: ['ADMIN', 'HR'],
  COMPANY_SETTINGS: ['ADMIN', 'HR'],
  NOTIFICATION_SETTINGS: ALL_ROLES,
  INTEGRATIONS: ['ADMIN'],
  HOLIDAYS_SETTINGS: ['ADMIN', 'HR'],
  DOCUMENTS: ['ADMIN', 'HR'],
  AI_ACTIONS: ['ADMIN'],
  REMOTE_WORK: ALL_ROLES,
  APPEARANCE_SETTINGS: ['ADMIN'],
  ACTIVITY_TYPES: ['ADMIN'],
  TEMPLATES: ['ADMIN', 'HR'],
  SYSTEM_EXPORT: ['ADMIN'],
  DATA_CLEANUP: ['ADMIN'],
  FEEDBACK_REPORTS: ALL_ROLES, // All roles can view, but permissions enforced at API level
} satisfies Record<string, UserRole[]>;


